### ISSUE TITLE
PatternSyntaxException: Unexpected internal error near index 1

### ISSUE THREAD

**Issue by AlexAdasCca** [saiema/MuJava#13]
@saiema 
I tried to run the mujava++ tool according to the instructions, but I received the following exception from the error log:
Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.lang.String.replaceAll(Unknown Source)
	at visitor.DependencyVisitor.getQualifiedClassName(DependencyVisitor.java:359)
	at visitor.DependencyVisitor.visit(DependencyVisitor.java:99)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at main.api.DependencyScanner.scan(DependencyScanner.java:91)
	at main.api.DependencyScanner.<init>(DependencyScanner.java:53)
	at mujava.util.Config.getpackagesInOriginalBinDir(Config.java:1083)
	at mujava.util.Config.clearPackagesInOriginalBinDir(Config.java:1225)
	at mujava.util.Config.<init>(Config.java:176)
	at mujava.util.ConfigReader.buildConfig(ConfigReader.java:660)
	at mujava.app.Main.main(Main.java:102)

And:
Parsing : jar:file:/H:/mjExample/mujava++.jar!/mujava/app/mutantsInfo.xml

**Comment by saiema** [comment]
Sorry for the delay, it's been a long time since I worked in this project. I would need to see the configuration file you are using, it appears that the error lies in the contents of that file.
